name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.77.0
          cache: false
      - run: pixi run lint

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.77.0
          cache: false
      - run: pixi run test

  visual-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.77.0
          cache: false
      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb xauth libgl1-mesa-dri mesa-utils libegl1 libglx-mesa0
      - run: pixi run test-visual-xvfb
